#!/usr/bin/env ruby
require 'fog'
require 'erb'
require 'json'
require 'terminal-table'
require_relative './lib/text_formatter'
require_relative './lib/html_formatter'

class ServerInfo

  def initialize
    @keys = YAML.load(File.read(File.join(File.dirname(File.realdirpath(__FILE__)) + "/keys.yaml")))
  rescue
    puts "You need to have a keys.yaml file with your amazon credentials in it."
    puts "Check out the keys.yaml.example for the format.  No quotes around the credentials."
    exit
  end

  def keys
    @keys.keys
  end

  def server_group(group_name)
    group = group_name.downcase
    server_group = []
    server_group << [group_name, Fog::Compute.new(provider: "AWS", aws_secret_access_key: @keys[group_name]["aws_secret_access_key"], aws_access_key_id: @keys[group_name]["aws_access_key_id"]).servers ]
    server_group
  end

  def display(group, formatter)
    group = server_group(group)
    formatter.new.format(group)
  end
end


si = ServerInfo.new

if(ARGV.count == 0)
  puts "Usage:  ./list_servers <appname as in keys.yaml>"
  puts "  you currently have these defined in your keys.yaml"
  print "  #{si.keys} \n"
else
  si.display(ARGV[0], TextFormatter)
end
